### ISSUE TITLE
cannot add condition on total

### ISSUE THREAD

**Issue by rebornishard** [darryldecode/laravelshoppingcart-demo#1]
https://shoppingcart-demo.darrylfernandez.com/cart

thanks for great cart

**Comment by darryldecode** [comment]
@rebornishard thanks for the heads up! There is unused code forgot to remove. Fix already here https://github.com/darryldecode/laravelshoppingcart-demo/commit/267d8cb54c18d27d943e20ab3fb334b65b471278

**Comment by rebornishard** [comment]
@darryldecode welcome, thanks a lot, cheers, i'm on my way to learning this great cart
